#!/bin/bash
set -e

# ── Entrypoint for CastoPOST ─────────────────────────────────
# Generates config.php from environment variables if not
# already present in the /data volume, then starts services.

CONFIG="/data/config.php"

# ── Generate config.php from env vars if it hasn't been customized ──
if grep -q "your_secure_password" "$CONFIG" 2>/dev/null || [ ! -f "$CONFIG" ]; then
    echo "[castopost] Generating config.php from environment variables..."

    cat > "$CONFIG" << PHPEOF
<?php
// ============================================================
//  CastoPOST - Auto-generated configuration
//  Generated by Docker entrypoint from environment variables.
//  You can also edit this file directly in your /data volume.
// ============================================================

define('APP_PASSWORD',            '${APP_PASSWORD:-change_me_now}');
define('CASTOPOD_URL',            '${CASTOPOD_URL:-https://your-castopod.com}');
define('CASTOPOD_API_USER',       '${CASTOPOD_API_USER:-api_user}');
define('CASTOPOD_API_PASSWORD',   '${CASTOPOD_API_PASSWORD:-api_password}');
define('CASTOPOD_PODCAST_HANDLE', '${CASTOPOD_PODCAST_HANDLE:-my-podcast}');
define('CASTOPOD_USER_ID',        ${CASTOPOD_USER_ID:-1});

define('PODCASTS_FILE',  __DIR__ . '/podcasts.json');
define('DRAFTS_FILE',    __DIR__ . '/local_drafts.json');
define('TEMPLATES_FILE', __DIR__ . '/templates.json');
define('UPLOAD_TMP_DIR', __DIR__ . '/tmp');

define('MAX_AUDIO_SIZE', ${MAX_AUDIO_SIZE:-536870912});

date_default_timezone_set('${APP_TIMEZONE:-UTC}');

define('CASTOPOD_DEBUG', ${CASTOPOD_DEBUG:-false});
PHPEOF

    echo "[castopost] config.php written."
fi

# ── Set PHP timezone ─────────────────────────────────────────
if [ -n "$APP_TIMEZONE" ]; then
    echo "date.timezone = ${APP_TIMEZONE}" >> /usr/local/etc/php/conf.d/castopost.ini
fi

# ── Ensure data files exist ──────────────────────────────────
[ -f /data/podcasts.json ]     || echo '[]'  > /data/podcasts.json
[ -f /data/local_drafts.json ] || echo '{}'  > /data/local_drafts.json
[ -f /data/templates.json ]    || echo '[]'  > /data/templates.json
mkdir -p /data/tmp

chown -R castopost:castopost /data
chmod 700 /data/tmp
chmod 664 /data/podcasts.json /data/local_drafts.json /data/templates.json

# ── Create Nginx temp dirs ───────────────────────────────────
mkdir -p /tmp/nginx_client_body /tmp/nginx_proxy /tmp/nginx_fastcgi \
         /tmp/nginx_uwsgi /tmp/nginx_scgi
chown -R castopost:castopost /tmp/nginx_*

# ── Start PHP-FPM ────────────────────────────────────────────
echo "[castopost] Starting PHP-FPM..."
php-fpm --daemonize --fpm-config /usr/local/etc/php-fpm.conf

# ── Start Nginx ──────────────────────────────────────────────
echo "[castopost] Starting Nginx on port 8080..."
exec nginx -g "daemon off;"
